-- Class Handler file for -- ----------------------------------------------------------------------------
--  This file was automatically generated by SWIG (http://www.swig.org).
--  Version 0.0.0
-- 
--  Do not make changes to this file unless you know what you are doing--modify
--  the SWIG interface file instead.
-- ----------------------------------------------------------------------------- */

import Foreign.Ptr
import Foreign.C

module NamedDog where

-- (inheritance, interfaces not supported yet)

}
-- (modifiers not supported yet)
-- TODO: emit destructor

-- (proxyClassFunctionDefinitionHandler  for )
  foreign import ccall "new_NamedDog"
     :: WhateverPtr -> CString -> IO WordPtr


  foreign import ccall "NamedDog"
    new :: CString -> IO WhateverPtr
-- (proxyClassFunctionDefinitionHandler setUnrelatedField for NamedDog_unrelatedField_set)
  foreign import ccall "NamedDog_unrelatedField_set"
    setUnrelatedField :: WhateverPtr -> WordPtr -> CString -> IO ()


-- (proxyClassFunctionDefinitionHandler getUnrelatedField for NamedDog_unrelatedField_get)
  foreign import ccall "NamedDog_unrelatedField_get"
    getUnrelatedField :: WhateverPtr -> WordPtr -> IO CString



  }

-- (proxyClassFunctionDefinitionHandler  for )
  foreign import ccall "delete_NamedDog"
     :: WhateverPtr -> WordPtr -> IO ()


-- TOOD: emit destructor

constructNamedDogRecord this = NamedDog

