-- Class Handler file for -- ----------------------------------------------------------------------------
--  This file was automatically generated by SWIG (http://www.swig.org).
--  Version 0.0.0
-- 
--  Do not make changes to this file unless you know what you are doing--modify
--  the SWIG interface file instead.
-- ----------------------------------------------------------------------------- */

import Foreign.Ptr
import Foreign.C

data Animal = Animal {
  -- (proxyClassFunctionDeclarationHandler setName for Animal_setName)
  setName :: String -> IO ()
  -- (proxyClassFunctionDeclarationHandler getName for Animal_getName)
  getName :: IO String
-- (inheritance, interfaces not supported yet)

}
-- (modifiers not supported yet)
-- TODO: emit destructor

-- (proxyClassFunctionDefinitionHandler setName for Animal_setName)
impl_Animal_setName :: WordPtr -> String -> IO ()
impl_Animal_setName this a0 = do
  c_Animal_setName this (tconvStringToCString a0)

-- (proxyClassFunctionDefinitionHandler getName for Animal_getName)
impl_Animal_getName :: WordPtr -> IO String
impl_Animal_getName this = do
  c_Animal_getName this 

-- TOOD: emit destructor

constructAnimalRecord this = Animal a0 a1
  where a0 = impl_Animal_setName this,
        a1 = impl_Animal_getName this

