-- Class Handler file for -- ----------------------------------------------------------------------------
--  This file was automatically generated by SWIG (http://www.swig.org).
--  Version 2.0.7
-- 
--  Do not make changes to this file unless you know what you are doing--modify
--  the SWIG interface file instead.
-- ----------------------------------------------------------------------------- */

type Animal = Animal {
  -- (proxyClassFunctionDeclarationHandler setName for Animal_setName)
  setName :: String -> IO ()
  -- (proxyClassFunctionDeclarationHandler getName for Animal_getName)
  getName :: IO String

-- (inheritance, interfaces not supported yet)

}
-- (modifiers not supported yet)

-- (proxyClassFunctionDefinitionHandler setName for Animal_setName)
proto_setName :: Ptr -> String -> IO ()
proto_setName this a = do
  $magifuncnametodo this -- TODO a
  (your_class_name_here! yeah!! (reconstructor]) 
-- (proxyClassFunctionDefinitionHandler getName for Animal_getName)
proto_getName :: Ptr -> IO String
proto_getName this = do
  $magifuncnametodo this 
  (your_class_name_here! yeah!! (reconstructor]) 
createAnimal :: IO (Animal)
createAnimal = Animal (lambda_proto_setName) (lambda_proto_getName) 
  where placeholder0idonotunderstandhaskelllininguprules = ()
        lambda_proto_setName = proto_setName objptr
        lambda_proto_getName = proto_getName objptr
  where placeholder0idonotunderstandhaskelllininguprules = ()

}
