-- Class Handler file for -- ----------------------------------------------------------------------------
--  This file was automatically generated by SWIG (http://www.swig.org).
--  Version 2.0.7
-- 
--  Do not make changes to this file unless you know what you are doing--modify
--  the SWIG interface file instead.
-- ----------------------------------------------------------------------------- */

type Cat = Cat {
  -- (proxyClassFunctionDeclarationHandler meow for Cat_meow)
  meow :: IO ()

-- (inheritance, interfaces not supported yet)

}
-- (modifiers not supported yet)

-- (proxyClassFunctionDefinitionHandler meow for Cat_meow)
proto_meow :: Ptr -> IO ()
proto_meow this = do
  $magifuncnametodo this 
  (your_class_name_here! yeah!! (reconstructor]) 
  public Cat() 
createCat :: IO (Cat)
createCat = Cat (lambda_proto_meow) 
  where placeholder0idonotunderstandhaskelllininguprules = ()
        lambda_proto_meow = proto_meow objptr
  where placeholder0idonotunderstandhaskelllininguprules = ()

}
