-- Class Handler file for -- ----------------------------------------------------------------------------
--  This file was automatically generated by SWIG (http://www.swig.org).
--  Version 0.0.0
-- 
--  Do not make changes to this file unless you know what you are doing--modify
--  the SWIG interface file instead.
-- ----------------------------------------------------------------------------- */

import Foreign.Ptr
import Foreign.C

data Cat = Cat {
  -- (proxyClassFunctionDeclarationHandler meow for Cat_meow)
  meow :: IO ()
-- (inheritance, interfaces not supported yet)

}
-- (modifiers not supported yet)
-- TODO: emit destructor

-- (proxyClassFunctionDefinitionHandler meow for Cat_meow)
impl_Cat_meow :: WordPtr -> IO ()
impl_Cat_meow this = do
  c_Cat_meow this 

newCat :: IO Cat
newCat = do
  constructCatRecord (c_new_Cat)
-- TOOD: emit destructor

constructCatRecord this = Cat a0
  where a0 = impl_Cat_meow this

