-- Class Handler file for -- ----------------------------------------------------------------------------
--  This file was automatically generated by SWIG (http://www.swig.org).
--  Version 2.0.7
-- 
--  Do not make changes to this file unless you know what you are doing--modify
--  the SWIG interface file instead.
-- ----------------------------------------------------------------------------- */

type Dog = Dog {
  -- (proxyClassFunctionDeclarationHandler bark for Dog_bark)
  bark :: IO ()

-- (inheritance, interfaces not supported yet)

}
-- (modifiers not supported yet)

-- (proxyClassFunctionDefinitionHandler bark for Dog_bark)
proto_bark :: Ptr -> IO ()
proto_bark this = do
  $magifuncnametodo this 
  (your_class_name_here! yeah!! (reconstructor]) 
  public Dog() 
createDog :: IO (Dog)
createDog = Dog (lambda_proto_bark) 
  where placeholder0idonotunderstandhaskelllininguprules = ()
        lambda_proto_bark = proto_bark objptr
  where placeholder0idonotunderstandhaskelllininguprules = ()

}
