-- Class Handler file for -- ----------------------------------------------------------------------------
--  This file was automatically generated by SWIG (http://www.swig.org).
--  Version 0.0.0
-- 
--  Do not make changes to this file unless you know what you are doing--modify
--  the SWIG interface file instead.
-- ----------------------------------------------------------------------------- */

import Foreign.Ptr
import Foreign.C

data Dog = Dog {
  -- (proxyClassFunctionDeclarationHandler bark for Dog_bark)
  bark :: IO ()
-- (inheritance, interfaces not supported yet)

}
-- (modifiers not supported yet)
-- TODO: emit destructor

-- (proxyClassFunctionDefinitionHandler bark for Dog_bark)
impl_Dog_bark :: WordPtr -> IO ()
impl_Dog_bark this = do
  c_Dog_bark this 

newDog :: IO Dog
newDog = do
  constructDogRecord (c_new_Dog)
-- TOOD: emit destructor

constructDogRecord this = Dog a0
  where a0 = impl_Dog_bark this

