-- Class Handler file for -- ----------------------------------------------------------------------------
--  This file was automatically generated by SWIG (http://www.swig.org).
--  Version 0.0.0
-- 
--  Do not make changes to this file unless you know what you are doing--modify
--  the SWIG interface file instead.
-- ----------------------------------------------------------------------------- */

import Foreign.Ptr
import Foreign.C

data NamedDog = NamedDog {
  -- (proxyClassFunctionDeclarationHandler setUnrelatedField for NamedDog_unrelatedField_set)
  setUnrelatedField ::  -> String -> IO ()
  -- (proxyClassFunctionDeclarationHandler getUnrelatedField for NamedDog_unrelatedField_get)
  getUnrelatedField ::  -> IO String
-- (inheritance, interfaces not supported yet)

}
-- (modifiers not supported yet)
-- TODO: emit destructor

newNamedDog :: String -> IO NamedDog
newNamedDog p0 = do
  constructNamedDogRecord (c_new_NamedDog p0)
-- (proxyClassFunctionDefinitionHandler setUnrelatedField for NamedDog_unrelatedField_set)
impl_NamedDog_setUnrelatedField :: WordPtr ->  -> String -> IO ()
impl_NamedDog_setUnrelatedField this a0 a1 = do
  c_NamedDog_setUnrelatedField this ( a0)(tconvStringToCString a1)

-- (proxyClassFunctionDefinitionHandler getUnrelatedField for NamedDog_unrelatedField_get)
impl_NamedDog_getUnrelatedField :: WordPtr ->  -> IO String
impl_NamedDog_getUnrelatedField this a0 = do
  c_NamedDog_getUnrelatedField this ( a0)


  }

-- TOOD: emit destructor

constructNamedDogRecord this = NamedDog

