-- intermediary class
-- ----------------------------------------------------------------------------
--  This file was automatically generated by SWIG (http://www.swig.org).
--  Version 0.0.0
-- 
--  Do not make changes to this file unless you know what you are doing--modify
--  the SWIG interface file instead.
-- ----------------------------------------------------------------------------- */

import Foreign.Ptr
import Foreign.C

-- todo: valid haskell for imports

foreign import ccall "Animal_setName"
  c_Animal_setName :: WordPtr -> CString -> IO ()
foreign import ccall "Animal_getName"
  c_Animal_getName :: WordPtr -> IO CString
foreign import ccall "delete_Animal"
  c_delete_Animal :: WordPtr -> IO ()
foreign import ccall "Dog_bark"
  c_Dog_bark :: WordPtr -> IO ()
foreign import ccall "new_Dog"
  c_new_Dog :: IO WordPtr
foreign import ccall "delete_Dog"
  c_delete_Dog :: WordPtr -> IO ()
foreign import ccall "new_NamedDog"
  c_new_NamedDog :: CString -> IO WordPtr
foreign import ccall "NamedDog_unrelatedField_set"
  c_NamedDog_unrelatedField_set :: WordPtr -> CString -> IO ()
foreign import ccall "NamedDog_unrelatedField_get"
  c_NamedDog_unrelatedField_get :: WordPtr -> IO CString
foreign import ccall "delete_NamedDog"
  c_delete_NamedDog :: WordPtr -> IO ()
foreign import ccall "Cat_meow"
  c_Cat_meow :: WordPtr -> IO ()
foreign import ccall "new_Cat"
  c_new_Cat :: IO WordPtr
foreign import ccall "delete_Cat"
  c_delete_Cat :: WordPtr -> IO ()
