-- intermediary class
-- ----------------------------------------------------------------------------
--  This file was automatically generated by SWIG (http://www.swig.org).
--  Version 2.0.7
-- 
--  Do not make changes to this file unless you know what you are doing--modify
--  the SWIG interface file instead.
-- ----------------------------------------------------------------------------- */

-- todo: valid haskell for imports

foreign import ccall "Animal_setName"
  c_TestingCppPINVOKE_Animal_setName :: Ptr -> CString -> IO ()
foreign import ccall "Animal_getName"
  c_TestingCppPINVOKE_Animal_getName :: Ptr -> IO CString
foreign import ccall "delete_Animal"
  c_TestingCppPINVOKE_delete_Animal :: Ptr -> IO ()
foreign import ccall "Dog_bark"
  c_TestingCppPINVOKE_Dog_bark :: Ptr -> IO ()
foreign import ccall "new_Dog"
  c_TestingCppPINVOKE_new_Dog :: IO Ptr
foreign import ccall "delete_Dog"
  c_TestingCppPINVOKE_delete_Dog :: Ptr -> IO ()
foreign import ccall "Cat_meow"
  c_TestingCppPINVOKE_Cat_meow :: Ptr -> IO ()
foreign import ccall "new_Cat"
  c_TestingCppPINVOKE_new_Cat :: IO Ptr
foreign import ccall "delete_Cat"
  c_TestingCppPINVOKE_delete_Cat :: Ptr -> IO ()
